name: swim-adsb
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
      - git+https://git@github.com/eurocontrol-swim/rest-client.git
      - git+https://git@github.com/eurocontrol-swim/opensky-network-client.git
      - git+https://git@github.com/eurocontrol-swim/subscription-manager-client.git
      - git+https://git@github.com/eurocontrol-swim/swim-qpid-proton.git
      - git+https://git@github.com/eurocontrol-swim/pubsub-facades.git
      - git+https://git@github.com/eurocontrol-swim/swim-backend.git
      - python-qpid_proton
      - cachetools
