name: swim-adsb
dependencies:
  - python
  - pytest
  - pytest-cov
  - pip:
      - git+ssh://git@bitbucket.org/antavelos-eurocontrol/rest-client.git
      - git+ssh://git@bitbucket.org/antavelos-eurocontrol/opensky-network-client.git
      - git+ssh://git@bitbucket.org/antavelos-eurocontrol/swim-pubsub.git