name: swim-adsb
dependencies:
  - python=3.9.7
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - pyyaml=6.0
  - attrs=21.4.0
  - packaging=21.3
  - pip=21.2.4
  - pip:
      - cachetools==5.0.0
      - requests==2.27.1
      - python-qpid-proton==0.36.0
      - pymongo==4.0
      - mongoengine==0.24.0
      - redis==4.1.4
      - urllib3==1.26.8
      # Keeping GitHub repository links for private packages
      - git+https://git@github.com/eurocontrol-swim/opensky-network-client.git@0.0.7
      - git+https://git@github.com/eurocontrol-swim/pubsub-facades.git@0.1.0
      - git+https://git@github.com/eurocontrol-swim/rest-client.git@0.1.1
      - git+https://git@github.com/eurocontrol-swim/subscription-manager-client.git@0.0.10
      - git+https://git@github.com/eurocontrol-swim/swim-backend.git@0.0.8
      - git+https://git@github.com/eurocontrol-swim/swim-qpid-proton.git@0.3.0